var hierarchy =
[
    [ "Application", null, [
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ]
    ] ],
    [ "System.Windows.Application", null, [
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ]
    ] ],
    [ "FractalCore.BaseScaffold", "class_fractal_core_1_1_base_scaffold.html", [
      [ "FractalCore.FractalFrame", "class_fractal_core_1_1_fractal_frame.html", [
        [ "FractalCore.Fractal", "class_fractal_core_1_1_fractal.html", null ]
      ] ]
    ] ],
    [ "BootstrapperBase", null, [
      [ "FractalGeneratorMVVM.Bootstrapper", "class_fractal_generator_m_v_v_m_1_1_bootstrapper.html", null ]
    ] ],
    [ "Conductor", null, [
      [ "FractalGeneratorMVVM.ViewModels.ShellViewModelOld", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_shell_view_model_old.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.Windows.DefaultWindowViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_windows_1_1_default_window_view_model.html", [
        [ "FractalGeneratorMVVM.ViewModels.Windows.NoMaxWindowViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_windows_1_1_no_max_window_view_model.html", null ]
      ] ]
    ] ],
    [ "FractalCore.FractalImage", "class_fractal_core_1_1_fractal_image.html", null ],
    [ "FractalGeneratorMVVM.Bootstrapper.FractalObjectPackage", "struct_fractal_generator_m_v_v_m_1_1_bootstrapper_1_1_fractal_object_package.html", null ],
    [ "System.Windows.Markup.IComponentConnector", null, [
      [ "FractalGeneratorMVVM.App", "class_fractal_generator_m_v_v_m_1_1_app.html", null ],
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.LabeledTextBox", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_labeled_text_box.html", null ],
      [ "FractalGeneratorMVVM.Controls.LabeledTextBox", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_labeled_text_box.html", null ],
      [ "FractalGeneratorMVVM.Controls.LabeledTextBox", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_labeled_text_box.html", null ],
      [ "FractalGeneratorMVVM.MainWindow", "class_fractal_generator_m_v_v_m_1_1_main_window.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.DefaultPageViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_default_page_view_model.html", null ],
      [ "FractalGeneratorMVVM.Views.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ConsoleWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window.html", null ],
      [ "FractalGeneratorMVVM.Views.ConsoleWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbon", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FormulaStack", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack.html", null ],
      [ "FractalGeneratorMVVM.Views.FormulaStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStack", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.MainWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window.html", null ],
      [ "FractalGeneratorMVVM.Views.MainWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.MainWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ModelViews.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_model_views_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ModelViews.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_model_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ModelViews.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_model_views_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.PainterBaseView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painter_base_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.PainterBaseView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_painter_base_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.PainterWhiteView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_painter_white_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.PainterWhiteView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_painter_white_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ]
    ] ],
    [ "FractalCore.IIterator", "interface_fractal_core_1_1_i_iterator.html", [
      [ "FractalCore.BasicIterator", "class_fractal_core_1_1_basic_iterator.html", null ]
    ] ],
    [ "System.Windows.Markup.InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "FractalCore.Painting.IPainter", "interface_fractal_core_1_1_painting_1_1_i_painter.html", [
      [ "FractalCore.Painting.BasicPainterBase", "class_fractal_core_1_1_painting_1_1_basic_painter_base.html", [
        [ "FractalCore.Painting.BasicPainterDark", "class_fractal_core_1_1_painting_1_1_basic_painter_dark.html", null ],
        [ "FractalCore.Painting.BasicPainterLight", "class_fractal_core_1_1_painting_1_1_basic_painter_light.html", null ]
      ] ],
      [ "FractalCore.Painting.BasicPainterDark", "class_fractal_core_1_1_painting_1_1_basic_painter_dark.html", null ],
      [ "FractalCore.Painting.BasicPainterLight", "class_fractal_core_1_1_painting_1_1_basic_painter_light.html", null ]
    ] ],
    [ "FractalGeneratorMVVM.ViewModels.Models.Painters.IPainterViewModel", "interface_fractal_generator_m_v_v_m_1_1_view_models_1_1_models_1_1_painters_1_1_i_painter_view_model.html", [
      [ "FractalGeneratorMVVM.ViewModels.Models.Painters.BasicPainterBaseViewModelAbstract", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_models_1_1_painters_1_1_basic_painter_base_view_model_abstract.html", [
        [ "FractalGeneratorMVVM.ViewModels.Models.Painters.BasicPainterDarkViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_models_1_1_painters_1_1_basic_painter_dark_view_model.html", null ],
        [ "FractalGeneratorMVVM.ViewModels.Models.Painters.BasicPainterLightViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_models_1_1_painters_1_1_basic_painter_light_view_model.html", [
          [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDESIGN", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_d_e_s_i_g_n.html", null ]
        ] ]
      ] ]
    ] ],
    [ "FractalGeneratorMVVM.Views.Models.IteratorDESIGN", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_d_e_s_i_g_n.html", null ],
    [ "FractalCore.Job", "class_fractal_core_1_1_job.html", [
      [ "FractalCore.FullRenderJob", "class_fractal_core_1_1_full_render_job.html", null ],
      [ "FractalCore.PaintJob", "class_fractal_core_1_1_paint_job.html", null ]
    ] ],
    [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView.MINMAXINFO", "struct_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view_1_1_m_i_n_m_a_x_i_n_f_o.html", null ],
    [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView.MINMAXINFO", "struct_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view_1_1_m_i_n_m_a_x_i_n_f_o.html", null ],
    [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView.MONITORINFO", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view_1_1_m_o_n_i_t_o_r_i_n_f_o.html", null ],
    [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView.MONITORINFO", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view_1_1_m_o_n_i_t_o_r_i_n_f_o.html", null ],
    [ "FormulaParser.Operator", "struct_formula_parser_1_1_operator.html", null ],
    [ "System.Windows.Controls.Page", null, [
      [ "FractalGeneratorMVVM.ViewModels.DefaultPageViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_default_page_view_model.html", null ]
    ] ],
    [ "FractalCore.Painting.PainterBase", "class_fractal_core_1_1_painting_1_1_painter_base.html", [
      [ "FractalCore.Painting.BasicPainterBase", "class_fractal_core_1_1_painting_1_1_basic_painter_base.html", null ]
    ] ],
    [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView.POINT", "struct_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view_1_1_p_o_i_n_t.html", null ],
    [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView.POINT", "struct_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view_1_1_p_o_i_n_t.html", null ],
    [ "TestingZone.Program", "class_testing_zone_1_1_program.html", null ],
    [ "PropertyChangedBase", null, [
      [ "FractalGeneratorMVVM.Kernel", "class_fractal_generator_m_v_v_m_1_1_kernel.html", null ]
    ] ],
    [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView.RECT", "struct_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view_1_1_r_e_c_t.html", null ],
    [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView.RECT", "struct_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view_1_1_r_e_c_t.html", null ],
    [ "FractalCore.RenderEngine", "class_fractal_core_1_1_render_engine.html", null ],
    [ "FractalCore.RenderProgressModel", "class_fractal_core_1_1_render_progress_model.html", null ],
    [ "FormulaParser.RPN", "class_formula_parser_1_1_r_p_n.html", null ],
    [ "FormulaParser.RPNToCL", "class_formula_parser_1_1_r_p_n_to_c_l.html", null ],
    [ "Screen", null, [
      [ "FractalGeneratorMVVM.ViewModels.Controls.CanvasViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_controls_1_1_canvas_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.Controls.FractalFrameStackViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_controls_1_1_fractal_frame_stack_view_model.html", [
        [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackDESIGN", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_d_e_s_i_g_n.html", null ]
      ] ],
      [ "FractalGeneratorMVVM.ViewModels.Controls.IteratorStackViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_controls_1_1_iterator_stack_view_model.html", [
        [ "FractalGeneratorMVVM.Views.Controls.IteratorStackDESIGN", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_d_e_s_i_g_n.html", null ]
      ] ],
      [ "FractalGeneratorMVVM.ViewModels.Controls.PainterStackViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_controls_1_1_painter_stack_view_model.html", [
        [ "FractalGeneratorMVVM.Views.Controls.PainterStackDESIGN", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_d_e_s_i_g_n.html", null ]
      ] ],
      [ "FractalGeneratorMVVM.ViewModels.Controls.StatusBarViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_controls_1_1_status_bar_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.Controls.ToolRibbonViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_controls_1_1_tool_ribbon_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.FractalFrameRowViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_fractal_frame_row_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.Models.FractalFrameViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_models_1_1_fractal_frame_view_model.html", [
        [ "FractalGeneratorMVVM.Views.Models.FractalFrameDESIGN", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_d_e_s_i_g_n.html", null ]
      ] ],
      [ "FractalGeneratorMVVM.ViewModels.Models.IteratorViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_models_1_1_iterator_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.Pages.ConsolePageViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_pages_1_1_console_page_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.Pages.DefaultPageViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_pages_1_1_default_page_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.PainterRowViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_painter_row_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.WinPages.AddFractalFrameWindowViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_win_pages_1_1_add_fractal_frame_window_view_model.html", null ],
      [ "FractalGeneratorMVVM.ViewModels.WinPages.AddPainterWindowViewModel", "class_fractal_generator_m_v_v_m_1_1_view_models_1_1_win_pages_1_1_add_painter_window_view_model.html", null ]
    ] ],
    [ "FractalCore.Status", "struct_fractal_core_1_1_status.html", null ],
    [ "FormulaParser.Token", "class_formula_parser_1_1_token.html", null ],
    [ "System.Windows.Controls.UserControl", null, [
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.FractalFrameItem", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_fractal_frame_item.html", null ],
      [ "FractalGeneratorMVVM.Controls.LabeledTextBox", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_labeled_text_box.html", null ],
      [ "FractalGeneratorMVVM.Controls.LabeledTextBox", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_labeled_text_box.html", null ],
      [ "FractalGeneratorMVVM.Controls.LabeledTextBox", "class_fractal_generator_m_v_v_m_1_1_controls_1_1_labeled_text_box.html", null ],
      [ "FractalGeneratorMVVM.Views.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ConsoleWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window.html", null ],
      [ "FractalGeneratorMVVM.Views.ConsoleWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbon", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ControlViews.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_control_views_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.CanvasView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_canvas_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Controls.ToolRibbonView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_controls_1_1_tool_ribbon_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FormulaStack", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack.html", null ],
      [ "FractalGeneratorMVVM.Views.FormulaStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStack", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ModelViews.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_model_views_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ModelViews.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_model_views_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ModelViews.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_model_views_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_fractal_frame_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.IteratorView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_iterator_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.PainterBaseView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painter_base_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterDarkView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_dark_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterLightView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_light_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.BasicPainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_basic_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.PainterBaseView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_painter_base_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.PainterWhiteView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_painter_white_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Models.Painters.PainterWhiteView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_models_1_1_painters_1_1_painter_white_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_console_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Pages.DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_pages_1_1_default_page_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", null ],
      [ "FractalGeneratorMVVM.Views.StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_status_bar_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.WinPages.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_add_painter_window_view.html", null ]
    ] ],
    [ "System.Windows.Window", null, [
      [ "FractalGeneratorMVVM.MainWindow", "class_fractal_generator_m_v_v_m_1_1_main_window.html", null ],
      [ "FractalGeneratorMVVM.Views.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.MainWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window.html", null ],
      [ "FractalGeneratorMVVM.Views.MainWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.MainWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_default_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ],
      [ "FractalGeneratorMVVM.Views.Windows.NoMaxWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_windows_1_1_no_max_window_view.html", null ]
    ] ]
];