var namespace_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages =
[
    [ "AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_fractal_frame_window_view" ],
    [ "AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages_1_1_add_painter_window_view" ]
];