var namespace_fractal_generator_m_v_v_m_1_1_views =
[
    [ "Controls", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_controls.html", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_controls" ],
    [ "ControlViews", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_control_views.html", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_control_views" ],
    [ "Models", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_models.html", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_models" ],
    [ "ModelViews", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_model_views.html", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_model_views" ],
    [ "Pages", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_pages.html", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_pages" ],
    [ "Windows", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_windows.html", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_windows" ],
    [ "WinPages", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages.html", "namespace_fractal_generator_m_v_v_m_1_1_views_1_1_win_pages" ],
    [ "AddFractalFrameWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_fractal_frame_window_view" ],
    [ "AddPainterWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window" ],
    [ "AddPainterWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_add_painter_window_view" ],
    [ "ConsolePageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_page_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_page_view" ],
    [ "ConsoleWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window" ],
    [ "ConsoleWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_console_window_view" ],
    [ "DefaultPageView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_page_view" ],
    [ "DefaultWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_window_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_default_window_view" ],
    [ "FormulaStack", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack" ],
    [ "FormulaStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_formula_stack_view" ],
    [ "FractalFrameRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_row_view" ],
    [ "FractalFrameStack", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack" ],
    [ "FractalFrameStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_stack_view" ],
    [ "FractalFrameView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_fractal_frame_view" ],
    [ "IteratorStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_iterator_stack_view" ],
    [ "MainWindow", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window" ],
    [ "MainWindowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_main_window_view" ],
    [ "PainterRowView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_row_view" ],
    [ "PainterStackView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_stack_view" ],
    [ "PainterView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_painter_view" ],
    [ "ShellView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view" ],
    [ "ShellViewOld", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_shell_view_old" ],
    [ "StatusBarView", "class_fractal_generator_m_v_v_m_1_1_views_1_1_status_bar_view.html", "class_fractal_generator_m_v_v_m_1_1_views_1_1_status_bar_view" ]
];